name: React CI

on:
  push:
    branches:
      - master   
         
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Build Static File
        run: npm run build

      - name: Test the app
        run: npm test

      - name: Configure aws Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static suite site  to s3 bucket
        run: aws s3 sync ./build s3://react-deploy-bucket
            
        