name: React CI

# on:
#   push:
#     branches:
#       - "master"

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [15.x]
    
#     steps:
#       - uses: actions/checkout@v1
#       - run: npm install
#       - run: npm run build
#       - run: npm test
#       - uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --acl public-read --follow-symlinks --delete
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_S3_BUCKET:  ${{ secrets.AWS_S3_BUCKET }}
#           AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
#           SOURCE_DIR: 'build'      # optional: defaults to entire repository



on:
  push:
    branches:
      - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}
#       - name: Install dependencies
#         run: npm install    
#       - name: Test
#         run: npm test
#         env:
#           CI: true
#       - name: Generate build
#         run: npm run build
#       - name: Share artifact inside workflow
#         uses: actions/upload-artifact@v1
#         with:
#           name: React-build
#           path: build
       
#       - name: Deploy app build to S3 bucket
#         run: aws s3 sync ./dist/ s3://react-deploy-bucket --delete
      
         
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Build Static File
        run: npm run build

      - name: Test the app
        run: npm test

      - name: Configure aws Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static suite site  to s3 bucket
        run: aws s3 sync ./build s3://react-deploy-bucket
            
        